const fullCitiesData = [
    { city: "Bhopal", lat: 23.2599, lon: 77.4126, areas: ["Shamla Hills", "MP Nagar", "Arera Colony", "Kerwa Dam", "Kolar Road"] },
    { city: "Indore", lat: 22.7196, lon: 75.8577, areas: ["Vijay Nagar", "Palasia", "Bhanwarkuan", "Super Corridor", "AB Road"] },
    { city: "Mumbai", lat: 19.0760, lon: 72.8777, areas: ["Bandra West", "Andheri East", "Colaba", "Juhu", "Powai"] },
    { city: "Pune", lat: 18.5204, lon: 73.8567, areas: ["Koregaon Park", "Viman Nagar", "Hinjewadi", "Baner", "Kalyani Nagar"] },
    { city: "Delhi", lat: 28.6139, lon: 77.2090, areas: ["Hauz Khas", "Connaught Place", "Vasant Kunj", "Karol Bagh", "Saket"] },
    { city: "Bengaluru", lat: 12.9716, lon: 77.5946, areas: ["Indiranagar", "Koramangala", "Whitefield", "Jayanagar", "HSR Layout"] },
    { city: "Jaipur", lat: 26.9124, lon: 75.7873, areas: ["C-Scheme", "Malviya Nagar", "Amer Road", "Vaishali Nagar", "Bani Park"] },
    { city: "Udaipur", lat: 24.5854, lon: 73.7125, areas: ["Pichola", "Fateh Sagar", "City Palace Road", "Ambrai Ghat", "Shikarbadi"] },
    { city: "Rishikesh", lat: 30.0869, lon: 78.2676, areas: ["Tapovan", "Laxman Jhula", "Ram Jhula", "Shivpuri"] },
    { city: "Shimla", lat: 31.1048, lon: 77.1734, areas: ["Mall Road", "Kufri", "Chhota Shimla", "Jakhu Hill"] },
    { city: "Goa", lat: 15.5937, lon: 73.7339, areas: ["Calangute", "Baga", "Panjim", "Anjuna", "Colva"] },
    { city: "Ahmedabad", lat: 23.0225, lon: 72.5714, areas: ["Satellite", "Prahlad Nagar", "Navrangpura", "Sindhu Bhavan"] },
    { city: "Hyderabad", lat: 17.3850, lon: 78.4867, areas: ["Banjara Hills", "Gachibowli", "Jubilee Hills", "HITEC City"] },
    { city: "Chennai", lat: 13.0827, lon: 80.2707, areas: ["Adyar", "Besant Nagar", "T-Nagar", "Mylapore"] },
    { city: "Kolkata", lat: 22.5726, lon: 88.3639, areas: ["Park Street", "Salt Lake", "New Town", "Gariahat", "Ballygunge"] },
    { city: "Chandigarh", lat: 30.7333, lon: 76.7794, areas: ["Sector 17", "Sector 35", "Sukhna Lake", "Mohali", "Panchkula"] },
    { city: "Surat", lat: 21.1702, lon: 72.8311, areas: ["Adajan", "Vesu", "Piplod", "Varachha", "Katargam"] },
    { city: "Lucknow", lat: 26.8467, lon: 80.9462, areas: ["Gomti Nagar", "Hazratganj", "Aliganj", "Indira Nagar", "Aminabad"] },
    { city: "Kochi", lat: 9.9312, lon: 76.2673, areas: ["Fort Kochi", "Marine Drive", "Edappally", "Kakkanad", "Mattancherry"] },
    { city: "Varanasi", lat: 25.3176, lon: 82.9739, areas: ["Assi Ghat", "Dashashwamedh Ghat", "Lanka", "Cantonment", "Sarnath"] },
    { city: "Nagpur", lat: 21.1458, lon: 79.0882, areas: ["Dharampeth", "Sitabuldi", "Civil Lines", "Manish Nagar", "Wardha Road"] },
    { city: "Patna", lat: 25.5941, lon: 85.1376, areas: ["Boring Road", "Kankarbagh", "Patliputra Colony", "Fraser Road", "Danapur"] },
    { city: "Visakhapatnam", lat: 17.6868, lon: 83.2185, areas: ["MVP Colony", "Gajuwaka", "Siripuram", "Rushikonda", "Jagadamba Junction"] },
    { city: "Guwahati", lat: 26.1445, lon: 91.7362, areas: ["Dispur", "Paltan Bazaar", "Ganeshguri", "Maligaon", "Uzan Bazar"] },
    { city: "Manali", lat: 32.2432, lon: 77.1892, areas: ["Old Manali", "Mall Road", "Vashisht", "Solang Valley"] },
    { city: "Coimbatore", lat: 11.0168, lon: 76.9558, areas: ["Gandhipuram", "Peelamedu", "RS Puram", "Race Course", "Saibaba Colony"] },
    { city: "Madurai", lat: 9.9252, lon: 78.1198, areas: ["Anna Nagar", "K.Pudur", "Sellur", "Tallakulam", "Madurai Main"] },
    { city: "Mysuru", lat: 12.2958, lon: 76.6394, areas: ["Gokulam", "Jayalakshmipuram", "Kuvempunagar", "Vijayanagar", "J P Nagar"] },
    { city: "Jodhpur", lat: 26.2389, lon: 73.0243, areas: ["Sardarpura", "Ratanada", "Shastri Nagar", "Paota", "Chopasni Housing Board"] },
    { city: "Amritsar", lat: 31.6340, lon: 74.8723, areas: ["Golden Temple Road", "Ranjit Avenue", "Lawrence Road", "Putlighar", "Majitha Road"] },
    { city: "Ludhiana", lat: 30.9010, lon: 75.8573, areas: ["Sarabha Nagar", "Model Town", "Civil Lines", "BRS Nagar", "Pakhowal Road"] },
    { city: "Agra", lat: 27.1767, lon: 78.0081, areas: ["Tajganj", "Sanjay Place", "Dayal Bagh", "Sikandra", "Kamla Nagar"] },
    { city: "Kanpur", lat: 26.4499, lon: 80.3319, areas: ["Swaroop Nagar", "Civil Lines", "Kidwai Nagar", "Kalyanpur", "Jajmau"] },
    { city: "Gwalior", lat: 26.2183, lon: 78.1828, areas: ["Gola Ka Mandir", "Lashkar", "Morar", "City Centre", "Hazira"] },
    { city: "Aurangabad", lat: 19.8762, lon: 75.3433, areas: ["CIDCO", "Waluj", "Nirala Bazar", "Garkheda", "Paithan Road"] },
    { city: "Rajkot", lat: 22.3039, lon: 70.8022, areas: ["Kalavad Road", "Yagnik Road", "Race Course Road", "Bhakti Nagar", "University Road"] },
    { city: "Srinagar", lat: 34.0837, lon: 74.7973, areas: ["Lal Chowk", "Dal Lake", "Rajbagh", "Sonwar", "Hazratbal"] },
    { city: "Jammu", lat: 32.7266, lon: 74.8570, areas: ["Gandhi Nagar", "Trikuta Nagar", "Channi Himmat", "Janipur", "Bahu Fort"] },
    { city: "Thiruvananthapuram", lat: 8.5241, lon: 76.9366, areas: ["Kazhakkoottam", "Kowdiar", "Pattom", "East Fort", "Vizhinjam"] },
    { city: "Ranchi", lat: 23.3441, lon: 85.3096, areas: ["Lalpur", "Doranda", "Kanke", "Upper Bazar", "Bariatu"] },
    { city: "Raipur", lat: 21.2514, lon: 81.6296, areas: ["Shankar Nagar", "Civil Lines", "Tatibandh", "Pandri", "Naya Raipur"] },
    { city: "Dehradun", lat: 30.3165, lon: 78.0322, areas: ["Rajpur Road", "Jakhan", "Clement Town", "Ballupur", "ISBT"] },
    { city: "Vijayawada", lat: 16.5062, lon: 80.6480, areas: ["Benz Circle", "Governorpet", "Moghalrajpuram", "Gunadala", "Patamata"] },
    { city: "Vadodara", lat: 22.3072, lon: 73.1812, areas: ["Alkapuri", "Akota", "Gotri", "Sayajigunj", "Karelibaug"] },
    { city: "Nashik", lat: 19.9975, lon: 73.7898, areas: ["Gangapur Road", "Indira Nagar", "Panchavati", "Nashik Road", "Satpur"] },
    { city: "Meerut", lat: 28.9845, lon: 77.7064, areas: ["Shastri Nagar", "Pallavpuram", "Modipuram", "Civil Lines", "Saket"] },
    { city: "Faridabad", lat: 28.4089, lon: 77.3178, areas: ["Sector 15", "Sector 21", "NIT", "Surajkund", "Greater Faridabad"] },
    { city: "Ghaziabad", lat: 28.6692, lon: 77.4538, areas: ["Indirapuram", "Vaishali", "Kaushambi", "Raj Nagar Extension", "Vasundhara"] },
    { city: "Jabalpur", lat: 23.1815, lon: 79.9864, areas: ["Civil Lines", "Wright Town", "Vijay Nagar", "Madan Mahal", "Gwarighat"] },
    { city: "Guntur", lat: 16.3067, lon: 80.4365, areas: ["Brodipet", "Arundelpet", "Lakshmipuram", "Koretipadu", "Vidya Nagar"] },
    { city: "Solapur", lat: 17.6599, lon: 75.9064, areas: ["Jule Solapur", "Murarji Peth", "Navi Peth", "Hotgi Road", "Saat Rasta"] },
    { city: "Hubli-Dharwad", lat: 15.3647, lon: 75.1240, areas: ["Vidyanagar", "Gokul Road", "Keshwapur", "Malamaddi", "Sattur"] },
    { city: "Bareilly", lat: 28.3670, lon: 79.4304, areas: ["Civil Lines", "Rajendra Nagar", "Model Town", "Izzatnagar", "Rampur Garden"] },
    { city: "Moradabad", lat: 28.8386, lon: 78.7733, areas: ["Civil Lines", "Ram Ganga Vihar", "Majhola", "Budh Bazaar", "Kanth Road"] },
    { city: "Aligarh", lat: 27.8974, lon: 78.0880, areas: ["Civil Lines", "Ramghat Road", "Centre Point", "Kwarsi", "AMU Area"] },
    { city: "Jalandhar", lat: 31.3260, lon: 75.5762, areas: ["Model Town", "Adarsh Nagar", "Rama Mandi", "Nakodar Road", "Civil Lines"] },
    { city: "Tiruchirappalli", lat: 10.7905, lon: 78.7047, areas: ["Thillai Nagar", "Cantonment", "Srirangam", "Woraiyur", "KK Nagar"] },
    { city: "Bhubaneswar", lat: 20.2961, lon: 85.8245, areas: ["Nayapalli", "Saheed Nagar", "Khandagiri", "Patia", "Unit 9"] },
    { city: "Salem", lat: 11.6643, lon: 78.1460, areas: ["Alagapuram", "Fairlands", "Shevapet", "Gugai", "Hasthampatti"] },
    { city: "Warangal", lat: 17.9689, lon: 79.5941, areas: ["Hanumakonda", "Kazipet", "Subedari", "Ramannapet", "Waddepally"] },
    { city: "Kota", lat: 25.2138, lon: 75.8648, areas: ["Talwandi", "Vigyan Nagar", "Landmark City", "Kunhari", "Dadabari"] },
    { city: "Prayagraj", lat: 25.4358, lon: 81.8463, areas: ["Civil Lines", "Katra", "Jhalwa", "Naini", "George Town"] },
    { city: "Dhanbad", lat: 23.7957, lon: 86.4304, areas: ["Steel Gate", "Hirapur", "Saraidhela", "Bank More", "Dhansar"] },
    { city: "Tirupati", lat: 13.6288, lon: 79.4192, areas: ["Tirumala", "KT Road", "Bhavani Nagar", "Kapilatheertham", "MR Palle"] },
    { city: "Mangaluru", lat: 12.9141, lon: 74.8560, areas: ["Bejai", "Kadri", "Surathkal", "Hampankatta", "Ullal"] },
    { city: "Noida", lat: 28.5355, lon: 77.3910, areas: ["Sector 18", "Sector 62", "City Center", "Pari Chowk", "Sector 15"] },
    { city: "Gurugram", lat: 28.4595, lon: 77.0266, areas: ["Cyber City", "DLF Phase 3", "Golf Course Road", "Sohna Road", "Sector 29"] },
    { city: "Amravati", lat: 20.9320, lon: 77.7523, areas: ["Rajapeth", "Gadge Nagar", "Sai Nagar", "Camp", "Badnera"] },
    { city: "Ajmer", lat: 26.4499, lon: 74.6399, areas: ["Vaishali Nagar", "Civil Lines", "Pushkar Road", "Adarsh Nagar", "Makarwali"] },
    { city: "Ujjain", lat: 23.1760, lon: 75.7885, areas: ["Freeganj", "Nanakheda", "Mahakal Marg", "Rishi Nagar", "Vedi Nagar"] },
    { city: "Bikaner", lat: 28.0229, lon: 73.3119, areas: ["Rani Bazar", "Jayanarayan Vyas Colony", "Civil Lines", "Gangashahar", "Pugal Road"] },
    { city: "Jhansi", lat: 25.4484, lon: 78.5685, areas: ["Civil Lines", "Sadar Bazar", "Sipri Bazar", "Elite Crossing", "Nandanpura"] },
    { city: "Jamnagar", lat: 22.4707, lon: 70.0577, areas: ["Digvijay Plot", "Khodiyar Colony", "Park Colony", "Shanti Nagar", "Gulabnagar"] },
    { city: "Saharanpur", lat: 29.9640, lon: 77.5460, areas: ["Court Road", "Gill Colony", "Mission Compound", "Avas Vikas", "Hakikat Nagar"] },
    { city: "Gaya", lat: 24.7914, lon: 85.0002, areas: ["Civil Lines", "Gaya College Road", "Bodh Gaya", "AP Colony", "Manpur"] },
    { city: "Siliguri", lat: 26.7271, lon: 88.3953, areas: ["Sevoke Road", "Hakim Para", "Khalpara", "Pradhan Nagar", "Matigara"] },
    { city: "Belagavi", lat: 15.8497, lon: 74.4977, areas: ["Tilakwadi", "Hindwadi", "Camp", "Bhagya Nagar", "Shahapur"] },
    { city: "Nellore", lat: 14.4426, lon: 79.9865, areas: ["Magunta Layout", "Vedayapalem", "Pogathota", "Mini Bypass Road", "Dargamitta"] },
    { city: "Kurnool", lat: 15.8281, lon: 78.0373, areas: ["Nandyal Checkpost", "C-Camp", "Gayatri Estate", "Budhawarapet", "Kallur"] },
    { city: "Rajamahendravaram", lat: 17.0005, lon: 81.8040, areas: ["Danavaipeta", "Tilak Road", "T Nagar", "Prakash Nagar", "Innespeta"] },
    { city: "Bhavnagar", lat: 21.7645, lon: 72.1519, areas: ["Kaliyabid", "Bharat Nagar", "Hill Drive", "Ghogha Circle", "Vidhyanagar"] },
    { city: "Bokaro Steel City", lat: 23.6693, lon: 86.1511, areas: ["Sector 4", "Sector 9", "City Centre", "Chas", "Sector 1"] },
    { city: "Rourkela", lat: 22.2604, lon: 84.8536, areas: ["Civil Township", "Koel Nagar", "Panposh", "Udit Nagar", "Chhend Colony"] },
    { city: "Bhilai", lat: 21.1938, lon: 81.3509, areas: ["Civic Centre", "Bhilai Hotel Area", "Risali", "Supela", "Nehru Nagar"] },
    { city: "Bilaspur", lat: 22.0797, lon: 82.1391, areas: ["Vyapar Vihar", "Rama Magneto Mall Area", "Civil Lines", "Tifra", "Sarkanda"] },
    { city: "Akola", lat: 20.7002, lon: 77.0082, areas: ["Civil Lines", "Jathar Peth", "Ramdas Peth", "Gorakshan Road", "Murtizapur Road"] },
    { city: "Jalgaon", lat: 21.0077, lon: 75.5626, areas: ["MG Road", "Ring Road", "Shivajinagar", "Jilha Peth", "Adarsh Nagar"] },
    { city: "Latur", lat: 18.4088, lon: 76.5604, areas: ["Ganjgolai", "MIDC", "Shivaji Nagar", "Prakash Nagar", "Ambajogai Road"] },
    { city: "Dhule", lat: 20.9042, lon: 74.7749, areas: ["Deopur", "Malegaon Road", "Sakri Road", "Wadi Bhokar Road", "Mhasawad"] },
    { city: "Ahmednagar", lat: 19.0948, lon: 74.7480, areas: ["Savedi", "Pipeline Road", "Gulmohar Road", "Taware Colony", "Kedgaon"] },
    { city: "Davanagere", lat: 14.4644, lon: 75.9218, areas: ["Vidyanagar", "MCC Layout", "PB Road", "PJ Extension", "Nittuvalli"] },
    { city: "Ballari", lat: 15.1394, lon: 76.9214, areas: ["Gandhinagar", "Cowl Bazaar", "Infanty Road", "Cantonment", "Ganesh Colony"] },
    { city: "Kalaburagi", lat: 17.3297, lon: 76.8343, areas: ["Sangameshwar Nagar", "MSK Mill", "SB Temple Road", "Sedam Road", "Brahmpur"] },
    { city: "Shivamogga", lat: 13.9299, lon: 75.5681, areas: ["Vinoba Nagar", "Gopala", "Jayanagar", "Gandhi Nagar", "Kuvempu Road"] },
    { city: "Tumakuru", lat: 13.3392, lon: 77.1140, areas: ["SS Puram", "SIT Extension", "Jayanagar", "Kyatsandra", "Batawadi"] },
    { city: "Thrissur", lat: 10.5276, lon: 76.2144, areas: ["Swaraj Round", "Punkunnam", "Ayyanthole", "Ollur", "Guruvayur Road"] },
    { city: "Kozhikode", lat: 11.2588, lon: 75.7804, areas: ["Mavoor Road", "Beach Road", "Nadakkavu", "Chevayur", "Kallai"] },
    { city: "Kollam", lat: 8.8932, lon: 76.6141, areas: ["Chinnakada", "Thirumullavaram", "Tangasseri", "Kadappakada", "Kilithattu"] },
    { city: "Tiruppur", lat: 11.1085, lon: 77.3411, areas: ["Palladam Road", "Avinashi Road", "Dharapuram Road", "Kumar Nagar", "Kangayam Road"] },
    { city: "Erode", lat: 11.3410, lon: 77.7172, areas: ["Perundurai Road", "Sampath Nagar", "Moolapalayam", "Kollampalayam", "Soolai"] },
    { city: "Vellore", lat: 12.9165, lon: 79.1325, areas: ["Katpadi", "Sathuvachari", "Gandhinagar", "Bagayam", "Arcot Road"] },
    { city: "Thanjavur", lat: 10.7870, lon: 79.1378, areas: ["Medical College Road", "Mary's Corner", "New Bus Stand", "Thanjavur Junction", "Karanthai"] },
    { city: "Kakinada", lat: 16.9891, lon: 82.2475, areas: ["Bhanugudi Junction", "Rama Rao Peta", "Srinagar", "Gaigolupadu", "Sarpavaram"] },
    { city: "Anantapur", lat: 14.6819, lon: 77.6006, areas: ["Rudrampeta", "Housing Board Colony", "Kamalanagar", "Maruthi Nagar", "Santhi Nagar"] },
    { city: "Karimnagar", lat: 18.4386, lon: 79.1288, areas: ["Kothirampur", "Mukarampura", "Bhagyanagar", "Jyothinagar", "Vavilalapalli"] },
    { city: "Eluru", lat: 16.7107, lon: 81.1035, areas: ["Powerpet", "Sanivarapupeta", "Ramachandra Rao Pet", "Pathebada"] },
    { city: "Ongole", lat: 15.5057, lon: 80.0493, areas: ["Santhapeta", "Bhagyanagar", "Mangamoor Road", "Lawyerpet"] },
    { city: "Itanagar", lat: 27.0844, lon: 93.6053, areas: ["Ganga Market", "Itafort", "Niti Vihar", "Vivek Vihar"] },
    { city: "Naharlagun", lat: 27.1044, lon: 93.6931, areas: ["E-Sector", "A-Sector", "Barapani", "Model Village"] },
    { city: "Dibrugarh", lat: 27.4728, lon: 94.9120, areas: ["Banipur", "Chowkidingee", "Amolapatty", "Jalan Nagar"] },
    { city: "Silchar", lat: 24.8333, lon: 92.7789, areas: ["Tarapur", "Ambikapatty", "Malugram", "Rangirkhari"] },
    { city: "Muzaffarpur", lat: 26.1209, lon: 85.3647, areas: ["Mithanpura", "Brahampura", "Mariapur", "Aghoria Bazar"] },
    { city: "Bhagalpur", lat: 25.2425, lon: 87.0135, areas: ["Adampur", "Khanjarpur", "Tilkamanjhi", "Barari"] },
    { city: "Korba", lat: 22.3595, lon: 82.7501, areas: ["Transport Nagar", "Balco Township", "Kusmunda", "TP Nagar"] },
    { city: "Durg", lat: 21.1905, lon: 81.2849, areas: ["Padmanabhpur", "Ganjpara", "Adarsh Nagar", "Sindhi Colony"] },
    { city: "Margao", lat: 15.2832, lon: 73.9862, areas: ["Fatorda", "Aquem", "Pajifond", "Gogol"] },
    { city: "Vasco da Gama", lat: 15.3959, lon: 73.8153, areas: ["Baina", "New Vaddem", "Mormugao Port", "Chicalim"] },
    { city: "Anand", lat: 22.5645, lon: 72.9289, areas: ["Vallabh Vidyanagar", "Amul Dairy Road", "Lambhvel Road", "Bakrol"] },
    { city: "Junagadh", lat: 21.5222, lon: 70.4579, areas: ["Zanzarda Road", "Timbawadi", "Moti Baug", "Kalwa Chowk"] },
    { city: "Ambala", lat: 30.3782, lon: 76.7767, areas: ["Ambala Cantt", "Model Town", "Prem Nagar", "Mahesh Nagar"] },
    { city: "Panipat", lat: 29.3909, lon: 76.9635, areas: ["Model Town", "Sanjay Colony", "Sector 11", "Sector 12"] },
    { city: "Dharamshala", lat: 32.2190, lon: 76.3234, areas: ["McLeod Ganj", "Kotwali Bazar", "Forsyth Ganj", "Dari"] },
    { city: "Solan", lat: 30.9045, lon: 77.0967, areas: ["Mall Road", "Chambaghat", "Deonghat", "Saproon"] },
    { city: "Jamshedpur", lat: 22.8046, lon: 86.2029, areas: ["Sakchi", "Bistupur", "Telco Colony", "Kadma", "Sonari"] },
    { city: "Hazaribagh", lat: 23.9925, lon: 85.3633, areas: ["Matwari", "Korrah", "Malviya Marg", "Pagal Khana Chowk"] },
    { city: "Raichur", lat: 16.2120, lon: 77.3439, areas: ["Sia Talab", "Basaveshwara Nagar", "IDSMT Layout", "Harihara Road"] },
    { city: "Bijapur", lat: 16.8302, lon: 75.7100, areas: ["Adarsh Nagar", "Golgumbaz Area", "Station Road", "Afzalpur Road"] },
    { city: "Alappuzha", lat: 9.4981, lon: 76.3388, areas: ["Finishing Point", "Punnamada", "Marari Beach", "Mullakkal"] },
    { city: "Palakkad", lat: 10.7867, lon: 76.6547, areas: ["Vidyut Nagar", "Olavakkode", "Chittur Road", "Kalpathy"] },
    { city: "Rewa", lat: 24.5362, lon: 81.3037, areas: ["Civil Lines", "Bodabagh", "Amahiya", "Saman"] },
    { city: "Sagar", lat: 23.8388, lon: 78.7378, areas: ["Civil Lines", "Makronia", "Tili", "Gopal Ganj"] },
    { city: "Kolhapur", lat: 16.7050, lon: 74.2433, areas: ["Rajarampuri", "Tarabai Park", "Shahupuri", "Kadamwadi"] },
    { city: "Sangli", lat: 16.8524, lon: 74.5815, areas: ["Vishrambag", "Miraj", "Madhavnagar", "Willingdon College Area"] },
    { city: "Imphal", lat: 24.8170, lon: 93.9368, areas: ["Kwakeithel", "Mantripukhri", "Sagolband", "Lamphelpat"] },
    { city: "Thoubal", lat: 24.6416, lon: 94.0152, areas: ["Thoubal Bazar", "Wangjing", "Athokpam", "Khongjom"] },
    { city: "Shillong", lat: 25.5788, lon: 91.8833, areas: ["Police Bazar", "Laitumkhrah", "Laband", "Upper Shillong"] },
    { city: "Tura", lat: 25.5141, lon: 90.2201, areas: ["Chandmari", "Dobasipara", "Hawakhana", "Araimile"] },
    { city: "Aizawl", lat: 23.7271, lon: 92.7176, areas: ["Zarkawt", "Bawkawn", "Mission Veng", "Chanmari"] },
    { city: "Lunglei", lat: 22.8870, lon: 92.7337, areas: ["Venglai", "Bazar Veng", "Salem Veng", "Lunglawn"] },
    { city: "Kohima", lat: 25.6747, lon: 94.1077, areas: ["High School Junction", "P.R. Hill", "Lower Chandmari", "Officer's Hill"] },
    { city: "Dimapur", lat: 25.9064, lon: 93.7266, areas: ["Duncan Basti", "Purana Bazar", "Kuda Village", "Signal Basti"] },
    { city: "Cuttack", lat: 20.4625, lon: 85.8830, areas: ["CDA Sector", "Buxi Bazar", "Mangalabag", "Link Road"] },
    { city: "Berhampur", lat: 19.3150, lon: 84.7941, areas: ["Gopalpur Road", "Brahmapur City", "Engineering School Road", "Kamapalli"] },
    { city: "Patiala", lat: 30.3398, lon: 76.3869, areas: ["Model Town", "Lehal", "Tripuri", "SST Nagar"] },
    { city: "Bathinda", lat: 30.2110, lon: 74.9455, areas: ["Model Town", "Civil Station", "Ganesha Basti", "Ajit Road"] },
    { city: "Alwar", lat: 27.5530, lon: 76.6346, areas: ["Matsya Industrial Area", "Budh Vihar", "Shivaji Park", "Nehru Garden"] },
    { city: "Bhilwara", lat: 25.3463, lon: 74.6364, areas: ["Shastri Nagar", "Subhash Nagar", "Azad Nagar", "Bapu Nagar"] },
    { city: "Gangtok", lat: 27.3314, lon: 88.6138, areas: ["MG Marg", "Deorali", "Tadong", "Arithang"] },
    { city: "Namchi", lat: 27.1672, lon: 88.3582, areas: ["Central Park", "Singithang", "Bhanjyang Road", "Boomtar"] },
    { city: "Tirunelveli", lat: 8.7139, lon: 77.7567, areas: ["Palayamkottai", "Maharajah Nagar", "Perumalpuram", "Vannarpettai"] },
    { city: "Thoothukudi", lat: 8.7973, lon: 78.1348, areas: ["Millerpuram", "Anna Nagar", "Polayarpuram", "Thermal Nagar"] },
    { city: "Nizamabad", lat: 18.6725, lon: 78.0941, areas: ["Kanteshwar", "Khaleelwadi", "Vinayak Nagar", "Arsapally"] },
    { city: "Khammam", lat: 17.2473, lon: 80.1514, areas: ["Wyra Road", "Mamillagudem", "Nizampet", "Rikab Bazar"] },
    { city: "Agartala", lat: 23.8315, lon: 91.2868, areas: ["Jaynagar", "Banamalipur", "Indranagar", "Ramnagar"] },
    { city: "Dharmanagar", lat: 24.3667, lon: 92.1667, areas: ["Bazar Area", "Nayapara", "Dewanpasa", "Rajbari"] },
    { city: "Gorakhpur", lat: 26.7606, lon: 83.3732, areas: ["Civil Lines", "Taramandal", "Golghar", "Medical College Road"] },
    { city: "Mathura", lat: 27.4924, lon: 77.6737, areas: ["Krishna Nagar", "Dampier Nagar", "Vrindavan Road", "Chowk Bazar"] },
    { city: "Haridwar", lat: 29.9457, lon: 78.1642, areas: ["Har Ki Pauri", "Kankhal", "Shivalik Nagar", "Jwalapur"] },
    { city: "Haldwani", lat: 29.2183, lon: 79.5130, areas: ["Mukhani", "Kathgodam", "Kaladhungi Road", "Nawabi Road"] },
    { city: "Durgapur", lat: 23.4807, lon: 87.3204, areas: ["City Centre", "Steel Township", "Benachity", "Bidhannagar"] },
    { city: "Asansol", lat: 23.6739, lon: 86.9524, areas: ["Burnpur", "Hutton Road", "Chelidanga", "Ushagram"] },
    { city: "Leh", lat: 34.1526, lon: 77.5770, areas: ["Main Bazar", "Chanspa", "Shanti Stupa Road", "Skalzangling"] },
    { city: "Port Blair", lat: 11.6234, lon: 92.7265, areas: ["Aberdeen Bazar", "Haddo", "Phoenix Bay", "Dollygunj"] },
    { city: "Puducherry", lat: 11.9416, lon: 79.8083, areas: ["White Town", "Heritage Town", "Lawspet", "Auroville Area"] },
    { city: "Silvassa", lat: 20.2763, lon: 73.0022, areas: ["Amli", "Tokarkhada", "Naroli", "Samarvarni"] },
];

export { fullCitiesData };